name: scrape
on:
  push:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  scrape-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install stuff
        run: |
          apt-get update
          apt-get install -y --no-install-recommends r-base python3 python3-pip r-cran-tidyverse
          pip3 install -r requirements.txt
      - name: run scripts
        run: python3 test.py #updateAll.py
        #run: Rscript clean.R
      - name: Create date file
        run: date +%s > last-run.txt
      - name: Commit report
        run: |
          git config --global user.name 'cluffa'
          git config --global user.email 'cluffa@users.noreply.github.com'
          git add -all
          git commit -am 'updated data'
          git push
